# Generated by Django 5.1.1 on 2024-10-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0003_addvehicle_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvehicle',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
