# Generated by Django 5.1.1 on 2024-10-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0006_alter_addvehicle_date_alter_addvehicle_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvehicle',
            name='img',
            field=models.ImageField(null=True, upload_to='myimage'),
        ),
        migrations.AlterField(
            model_name='addvehicle',
            name='name',
            field=models.CharField(max_length=122),
        ),
    ]
