# Generated by Django 5.1.1 on 2024-10-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0007_alter_addvehicle_img_alter_addvehicle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvehicle',
            name='date',
            field=models.DateField(),
        ),
    ]
